### ISSUE TITLE
www.openteventhub.com site is down

### ISSUE THREAD

**Issue by okains** [abpframework/eventhub#118]
503 Service Temporarily Unavailable

![image](https://user-images.githubusercontent.com/21369795/196661981-d63cd926-3440-4ace-b7ec-5f78dd7ce0df.png)

**Comment by berkansasmaz** [comment]
Thank you for reporting the issue. We will solve it as soon as possible.

**Comment by berkansasmaz** [comment]
The problem has been resolved. Thanks again.

**Comment by okains** [comment]
no problem, glad to help
