### ISSUE TITLE
Add ABP Framework version to footer

### ISSUE THREAD

**Issue by berkansasmaz** [abpframework/eventhub#122]
Related https://github.com/abpframework/abp/issues/13794

![186121978-18c7b865-7c4f-4617-a3f6-0863f3f24623](https://user-images.githubusercontent.com/31216880/208608220-9f8a95f6-768e-4e86-9024-bc3dbf5772ea.png)

**Comment by ebicoglu** [comment]
![image](https://user-images.githubusercontent.com/9526587/208618388-40095f72-533f-4710-b1e2-6a8c4294cfe9.png)
