### ISSUE TITLE
The underlying red line of selected menu item is not straight, a bit tilted

### ISSUE THREAD

**Issue by postmeback** [abpframework/eventhub#129]
Please refer the below screenshot

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/14862687/235412623-67313207-3e4b-4d19-b295-726f69e8e95e.png)

It seems that the underlying red line of the selected menu is not straight. Is it intentional or mistake ?. If it is a bug, then i would like to take it up as an issue.

**Comment by EngincanV** [comment]
Hi @postmeback, it's designed that way (intentional).
